#configurasi file .conf apache di /etc/apache2/site-available/namadomain.com.conf
<VirtualHost *:80>
    ServerName namadomain.pakarbot.com

    # Proxy untuk API (Main)
#    ProxyPass / http://127.0.0.1:8081/
 #   ProxyPassReverse / http://127.0.0.1:8081/
#langsung redirect aja semua ke https biar aman
Redirect permanent / https://evolutionapi.pakarbot.com/
    # Opsional: Jika ingin dashboard diakses via evolutionapi.pakarbot.com/dashboard
    # Anda perlu konfigurasi tambahan, namun cara termudah adalah
    # menggunakan port berbeda atau subdomain berbeda untuk dashboard.

    ErrorLog ${APACHE_LOG_DIR}/evolution_error.log
    CustomLog ${APACHE_LOG_DIR}/evolution_access.log combined
RewriteEngine on
RewriteCond %{SERVER_NAME} =namadomain.pakarbot.com
RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>
